<?php

namespace davidhirtz\yii2\skeleton\widgets\forms;

use davidhirtz\yii2\skeleton\db\ActiveRecord;
use davidhirtz\yii2\skeleton\helpers\Html;
use davidhirtz\yii2\skeleton\widgets\bootstrap\ActiveField;
use Yii;
use yii\base\Model;
use yii\helpers\Inflector;
use yii\helpers\Json;

/**
 * @method ActiveField field($model, $attribute, $options = [])
 */
trait ActiveFormTrait
{
    public ?Model $model = null;

    /**
     * @var array|null containing a list of fields that will be auto-generated.
     * @see ActiveFormTrait::renderFields()
     */
    public ?array $fields = null;

    /**
     * @var bool whether fields for unsafe attributes should be generated.
     */
    public bool $showUnsafeAttributes = false;

    /**
     * @var array|null containing the button config for the button row.
     * @see ActiveFormTrait::renderButtons()
     */
    public ?array $buttons = null;

    /**
     * @var bool whether a default submit button should be displayed.
     */
    public bool $showSubmitButton = true;

    /**
     * @var bool whether bottom buttons should be sticky
     */
    public bool $hasStickyButtons = false;

    /**
     * @var array|null containing a custom list of languages used for i18n-aware attributes.
     * Leave empty to use default languages.
     */
    public ?array $languages = null;

    /**
     * @var array|null containing a custom list of attribute names used for i18n-aware attributes.
     * Leave empty to use default 18n attribute.
     */
    public ?array $i18nAttributes = null;

    public function init(): void
    {
        if ($this->model) {
            if ($this->i18nAttributes === null) {
                $this->i18nAttributes = $this->model instanceof ActiveRecord ? $this->model->i18nAttributes : [];
            }

            if ($this->languages === null && $this->i18nAttributes) {
                $this->languages = Yii::$app->getI18n()->getLanguages();
            }

            if (!$this->getId(false)) {
                $this->setId(strtolower($this->model->formName()));
            }
        }

        parent::init();
    }

    public function run(): string
    {
        if ($this->model) {
            $this->renderHeader();
            $this->renderFields();
            $this->renderButtons();
            $this->renderFooter();
        }

        return parent::run();
    }

    /**
     * Renders the configured form fields.
     */
    public function renderFields(): void
    {
        if ($this->fields) {
            $safeAttributes = $this->model->safeAttributes();

            foreach ($this->fields as $fieldConfig) {
                if ($fieldConfig instanceof \yii\widgets\ActiveField) {
                    if ($this->showUnsafeAttributes || in_array($fieldConfig->attribute, $safeAttributes)) {
                        echo $fieldConfig;
                        continue;
                    }
                }

                $fieldConfig = (array)$fieldConfig;
                $attribute = array_shift($fieldConfig);

                if ($attribute) {
                    if (isset($fieldConfig[0]['visible'])) {
                        if ($fieldConfig[0]['visible'] === false) {
                            continue;
                        }

                        unset($fieldConfig[0]['visible']);
                    }

                    if ($attribute == '-') {
                        echo $this->horizontalLine();
                        continue;
                    }

                    if ($this->showUnsafeAttributes || in_array($attribute, $safeAttributes)) {
                        if (in_array($attribute, $this->i18nAttributes)) {
                            foreach ($this->languages as $language) {
                                $fieldConfig['options']['language'] = $language;
                                echo $this->getAutogeneratedField($attribute, $fieldConfig);
                            }
                        } else {
                            echo $this->getAutogeneratedField($attribute, $fieldConfig);
                        }
                    }
                }
            }
        }
    }

    /**
     * Renders i18n aware hidden input field for given attribute.
     */
    public function hiddenInputField(ActiveRecord $model, string $attribute): string
    {
        $fields = Html::activeHiddenInput($model, $attribute);

        if (in_array($attribute, $model->i18nAttributes)) {
            foreach ($this->languages as $language) {
                $fields .= Html::activeHiddenInput($model, Yii::$app->getI18n()->getAttributeName($attribute, $language));
            }
        }

        return $fields;
    }

    protected function getAutogeneratedField(string $attribute, array $fieldConfig = []): ActiveField|string
    {
        // Try to render field with custom method if the first field config is not a string or custom method.
        if (is_array($fieldConfig[0] ?? [])) {
            $methodName = lcfirst(Inflector::camelize($attribute)) . 'Field';

            if ($this->hasMethod($methodName)) {
                return call_user_func_array([$this, $methodName], array_filter($fieldConfig));
            }
        }

        if (isset($fieldConfig['options']['language'])) {
            $attribute = Yii::$app->getI18n()->getAttributeName($attribute, $fieldConfig['options']['language']);
            unset($fieldConfig['options']['language']);
        }

        if (($fieldConfig[0] ?? null) === 'hidden') {
            return $this->hiddenInputField($this->model, $attribute);
        }

        $options = isset($fieldConfig[0]) && is_array($fieldConfig[0]) ? array_shift($fieldConfig) : [];
        $type = isset($fieldConfig[0]) ? array_shift($fieldConfig) : 'text';

        $field = $this->field($this->model, $attribute, $options);
        $inputOptions = $fieldConfig[0] ?? [];

        if (in_array($type, ['email', 'number', 'password', 'text'])) {
            $field->input($type, $inputOptions);
        } elseif (method_exists($field, $type)) {
            call_user_func_array([$field, $type], $fieldConfig);
        } elseif (method_exists($this, $type)) {
            call_user_func_array([$this, $type], $fieldConfig);
        } else {
            $field->widget($type, $inputOptions);
        }

        // This hides empty dropdowns, etc.
        return $field->parts['{input}'] ? $field : '';
    }

    public function renderButtons(): void
    {
        $buttonRow = $this->buttonRow($this->buttons ?: ($this->showSubmitButton ? $this->button() : null));
        echo $buttonRow && $this->hasStickyButtons ? Html::tag('div', $buttonRow, ['class' => 'form-group-sticky']) : $buttonRow;
    }

    /**
     * Renders the footer.
     */
    public function renderHeader(): void
    {
    }

    /**
     * Renders the footer.
     */
    public function renderFooter(): void
    {
    }

    /**
     * @return string
     * @deprecated as the "render" methods should echo instead of return, please use
     * {@link ActiveFormTrait::horizontalLine()} instead.
     *
     */
    public function renderHorizontalLine(): string
    {
        return '<hr>';
    }

    /**
     * @return string
     */
    public function horizontalLine(): string
    {
        return '<hr>';
    }

    public function button(?string $label = null, array $options = ['class' => 'btn-primary']): string
    {
        if (!$label) {
            $label = $this->model instanceof ActiveRecord && $this->model->getIsNewRecord() ? Yii::t('skeleton', 'Create') : Yii::t('skeleton', 'Update');
        }

        if (!isset($options['type'])) {
            $options['type'] = 'submit';
        }

        Html::addCssClass($options, ['btn', 'btn-submit']);
        return Html::button($label, $options);
    }

    public function label(string $content, array $options = []): string
    {
        Html::addCssClass($options, $this->fieldConfig['horizontalCssClasses']['label']);
        return Html::tag('div', $content, $options);
    }

    public function input(string $content, array $options = []): string
    {
        Html::addCssClass($options, $this->fieldConfig['horizontalCssClasses']['input']);
        return Html::tag('div', $content, $options);
    }

    public function offset(string $content, array $options = []): string
    {
        Html::addCssClass($options, $this->fieldConfig['horizontalCssClasses']['offset']);
        return Html::tag('div', $content, $options);
    }

    public function row(string $content, array $options = []): string
    {
        Html::addCssClass($options, $this->fieldConfig['horizontalCssClasses']['field']);
        return Html::tag('div', $content, $options);
    }

    public function wrapper(string $content, array $options = []): string
    {
        Html::addCssClass($options, $this->fieldConfig['horizontalCssClasses']['wrapper']);
        return Html::tag('div', $content, $options);
    }

    public function buttonRow(array|string $buttons, array $options = []): string
    {
        return $buttons
            ? $this->row($this->offset(Html::buttons($buttons, $options)), ['class' => 'form-group-buttons'])
            : '';
    }

    public function labelRow(string $label, string $content, array $options = []): string
    {
        return $this->row($this->label($label) . $this->wrapper($content), $options);
    }

    public function plainTextRow(string $label, string $content, array $options = []): string
    {
        return $this->row($this->label($label)
            . $this->wrapper(Html::tag('div', $content, ['class' => 'form-control-plaintext'])), $options);
    }

    public function listRow(array $items, array $options = []): string
    {
        if (!$options) {
            $options = [
                'class' => 'list-unstyled small text-muted',
                'encode' => false,
            ];
        }

        return $this->textRow(Html::ul($items, $options));
    }

    public function textRow(string $content, array $options = []): string
    {
        return $this->row($this->offset(Html::formText($content, $options)));
    }

    /**
     * Encodes data toggle options of input fields. Attribute names can either be set via the fields key or as an array
     * with the values being the first value and the field names the second. Set languages to `false` to disable i18n.
     *
     * [
     *     'content' => [Section::TYPE_VISUAL],
     *     [[Section::TYPE_VISUAL], ['content'],
     * ],
     */
    public function getToggleOptions(array $fields, array|false|null $languages = null): array
    {
        $options = [];

        foreach ($fields as $name => $values) {
            if (is_int($name)) {
                [$values, $attributes] = $values;
            } else {
                $attributes = [$name];
            }

            if (method_exists($this->model, 'getI18nAttributesNames') && $languages !== false) {
                $attributes = $this->model->getI18nAttributesNames($attributes, $languages);
            }

            $selectors = [];

            foreach ($attributes as $attribute) {
                $selectors[] = $this->model->hasProperty($attribute) ? Html::getInputId($this->model, $attribute) : $attribute;
            }

            $options[] = [$values, $selectors];
        }

        return ['data-form-toggle' => Json::htmlEncode($options)];
    }
}