<?php

declare(strict_types=1);

namespace davidhirtz\yii2\skeleton\tests\unit\widgets\bootstrap;

use Codeception\Test\Unit;
use davidhirtz\yii2\skeleton\helpers\ArrayHelper;
use davidhirtz\yii2\skeleton\validators\DynamicRangeValidator;
use davidhirtz\yii2\skeleton\widgets\forms\ActiveForm;
use davidhirtz\yii2\skeleton\widgets\forms\fields\InputField;
use yii\base\Model;

class ActiveFormTest extends Unit
{
    public function testAttributeWithAutogeneratedFields(): void
    {
        $form = ActiveForm::make()
            ->model(new TestModel());

        $needle = '<input type="text" id="testmodel-custom" class="input" name="TestModel[custom]">';
        self::assertStringContainsString($needle, $form->render());
    }

    public function testAttributeWithAutogeneratedField(): void
    {
        $content = TestActiveForm::widget([
            'fields' => [
                'value',
            ],
        ]);

        $needle = '<input type="text" id="testmodel-value" class="input" name="TestModel[value]">';
        self::assertStringContainsString($needle, $content);

        $content = TestActiveForm::widget([
            'fields' => [
                ['value', 'hidden'],
            ],
        ]);

        $needle = '<input type="hidden" id="testmodel-value" class="input" name="TestModel[value]">';
        self::assertStringContainsString($needle, $content);

        $content = TestActiveForm::widget([
            'fields' => [
                ['value', 'textarea', 'fieldOptions' => [
                    'inputOptions' => ['rows' => 5],
                ]],
            ],
        ]);

        $needle = '<textarea id="testmodel-value" class="input" name="TestModel[value]" rows="5"></textarea>';
        self::assertStringContainsString($needle, $content);

        $content = TestActiveForm::widget([
            'fields' => [
                ['value', 'textarea', 'rows' => 5],
            ],
        ]);

        self::assertStringContainsString($needle, $content);

        $content = TestActiveForm::widget([
            'fields' => [
                [
                    'value',
                    'dropDownList',
                    'items' => ArrayHelper::getColumn(TestModel::getValues(), 'name'),
                ],
            ],
        ]);

        $needle = "<select id=\"testmodel-value\" class=\"select\" name=\"TestModel[value]\">\n<option value=\"value1\">Value 1</option>";
        self::assertStringContainsString($needle, $content);


        $content = TestActiveForm::widget([
            'fields' => [
                ['value', DynamicSelectField::class],
            ],
        ]);

        self::assertStringContainsString($needle, $content);
    }
}

class TestModel extends Model
{
    public ?string $number = null;
    public ?string $invalid = null;
    public ?string $value = null;

    public function rules(): array
    {
        return [
            [
                ['number'],
                'integer',
                'max' => 100,
            ],
            [
                ['value'],
                DynamicRangeValidator::class,
            ],
        ];
    }

    public static function getValues(): array
    {
        return [
            'value1' => [
                'name' => 'Value 1'
            ],
            'value2' => [
                'name' => 'Value 2'
            ],
            'value3' => [
                'name' => 'Value 3'
            ],
        ];
    }
}
