<?php

declare(strict_types=1);

namespace davidhirtz\yii2\skeleton\tests\unit\widgets\forms;

use Codeception\Test\Unit;
use davidhirtz\yii2\skeleton\html\Div;
use davidhirtz\yii2\skeleton\validators\DynamicRangeValidator;
use davidhirtz\yii2\skeleton\widgets\forms\ActiveForm;
use yii\base\Model;

class ActiveFormTest extends Unit
{
    public function testAttributeWithAutogeneratedFields(): void
    {
        $form = ActiveForm::make()
            ->model(new TestModel());

        $label = '<div class="form-label"><label class="label" for="testmodel-number">Number</label>';
        $number = '<div class="form-content"><input type="number" id="testmodel-number" class="input" name="TestModel[number]" max="100"></div>';
        $text = '<div class="form-content"><input type="text" id="testmodel-text" class="input" name="TestModel[text]" maxlength="50" minlength="50"></div>';
        $select = '<select id="testmodel-value" class="input" name="TestModel[value]"><option value="value1">Value 1</option><option value="value2">Value 2</option><option value="value3">Value 3</option></select>';

        $content = $form->render();

        self::assertStringContainsString($label, $content);
        self::assertStringContainsString($number, $content);
        self::assertStringContainsString($text, $content);
        self::assertStringContainsString($select, $content);
    }

    public function testAttributeWithMultipleFieldsets(): void
    {
        $form = ActiveForm::make()
            ->model(new TestModel())
            ->rows([
                [
                    Div::make()->content('Block 1'),
                    'number',
                ],
                [
                    Div::make()->content('Block 2'),
                    'text',
                ],
                [
                    'invalid',
                ],
            ]);

        $content = $form->render();

        self::assertStringContainsString('Block 1', $content);
        self::assertStringContainsString('<div class="form-label"><label class="label" for="testmodel-number">Number</label>', $content);
        self::assertStringContainsString('Block 2', $content);
        self::assertStringContainsString('<div class="form-label"><label class="label" for="testmodel-text">Text</label>', $content);
        self::assertStringNotContainsString('invalid', $content);
    }
}

class TestModel extends Model
{
    public ?string $number = null;
    public ?string $text = null;
    public ?string $invalid = null;
    public ?string $value = null;

    #[\Override]
    public function rules(): array
    {
        return [
            [
                ['number'],
                'integer',
                'max' => 100,
            ],
            [
                ['text'],
                'string',
                'length' => 50,
            ],
            [
                ['value'],
                DynamicRangeValidator::class,
            ],
        ];
    }

    public static function getValues(): array
    {
        return [
            'value1' => [
                'name' => 'Value 1'
            ],
            'value2' => [
                'name' => 'Value 2'
            ],
            'value3' => [
                'name' => 'Value 3'
            ],
        ];
    }
}
