<?php

declare(strict_types=1);

namespace davidhirtz\yii2\skeleton\tests\unit\widgets\forms;

use Codeception\Test\Unit;
use davidhirtz\yii2\skeleton\db\ActiveRecord;
use davidhirtz\yii2\skeleton\models\interfaces\I18nAttributeInterface;
use davidhirtz\yii2\skeleton\models\traits\I18nAttributesTrait;
use davidhirtz\yii2\skeleton\validators\SensitiveAttributeValidator;
use davidhirtz\yii2\skeleton\widgets\forms\fields\InputField;
use davidhirtz\yii2\skeleton\widgets\forms\Fieldset;
use Override;
use Yii;

class FieldsetTest extends Unit
{
    protected function _before(): void
    {
        Yii::$app->getI18n()->setLanguages(['en-US', 'de']);

        $columns = [
            'id' => 'pk',
            'name' => 'string not null',
            'name_de' => 'string not null',
            'email' => 'string null',
            'password' => 'string null',
            'terms' => 'boolean null',
            'number' => 'integer(2) unsigned not null',
        ];

        Yii::$app->getDb()->createCommand()
            ->createTable(TestActiveRecord::tableName(), $columns)
            ->execute();

        Yii::$app->getDb()->createCommand()
            ->insert(TestActiveRecord::tableName(), [
                'name' => 'Test Name',
                'name_de' => 'Test Name DE',
                'number' => 42,
            ])->execute();

        parent::_before();
    }

    protected function _after(): void
    {
        Yii::$app->getDb()->createCommand()
            ->dropTable(TestActiveRecord::tableName())
            ->execute();

        parent::_after();
    }

    public function testAutogeneratedFields(): void
    {
        $model = TestActiveRecord::findOne(1);

        $content = Fieldset::make()
            ->model($model)
            ->rows([
                'name',
                'number',
                'email',
                'password',
                'terms',
            ])
            ->render();

        $rows = [
            '<div class="form-group form-row" data-id="testactiverecord-name"><div class="form-label"><label class="label" for="testactiverecord-name">Name</label></div><div class="form-content"><input type="text" id="testactiverecord-name" class="input" name="TestActiveRecord[name]" value="Test Name" maxlength="255" required></div></div>',
            '<div class="form-group form-row" data-id="testactiverecord-name-de"><div class="form-label"><label class="label" for="testactiverecord-name-de">Name (DE)</label></div><div class="form-content"><input type="text" id="testactiverecord-name-de" class="input" name="TestActiveRecord[name_de]" value="Test Name DE" maxlength="255" required></div></div>',
            '<div class="form-group form-row" data-id="testactiverecord-email"><div class="form-label"><label class="label" for="testactiverecord-email">Email</label></div><div class="form-content"><input type="email" id="testactiverecord-email" class="input" name="TestActiveRecord[email]"></div></div>',
            '<div class="form-group form-row" data-id="testactiverecord-password"><div class="form-label"><label class="label" for="testactiverecord-password">Password</label></div><div class="form-content"><input type="password" id="testactiverecord-password" class="input" name="TestActiveRecord[password]"></div></div>',
            '<div class="form-checkbox-row form-group form-row" data-id="testactiverecord-terms"><div class="form-content"><div class="checkbox"><input type="checkbox" id="testactiverecord-terms" class="input" name="TestActiveRecord[terms]" value="1"></div><div><label class="label" for="testactiverecord-terms">Terms</label></div></div></div>',
        ];

        foreach ($rows as $row) {
            self::assertStringContainsString($row, $content);
        }
    }

    public function testI18nFields(): void
    {
        $model = TestActiveRecord::findOne(1);

        $content = Fieldset::make()
            ->model($model)
            ->rows([
                InputField::make()
                    ->property('name')
                    ->model($model)
                    ->prepare(fn (InputField $field) => $field->value($field->language)),
            ])
            ->render();

        $rows = [
            '<div id="testactiverecord-name-row" class="form-group form-row"><div class="form-label"><label class="label" for="testactiverecord-name">Name</label></div><div class="form-content"><input type="text" id="testactiverecord-name" class="input" name="TestActiveRecord[name]" value="en-US" maxlength="255" required></div></div>',
            '<div id="testactiverecord-name-de-row" class="form-group form-row"><div class="form-label"><label class="label" for="testactiverecord-name-de">Name (DE)</label></div><div class="form-content"><input type="text" id="testactiverecord-name-de" class="input" name="TestActiveRecord[name_de]" value="de" maxlength="255" required></div></div>',
        ];

        foreach($rows as $row) {
            self::assertStringContainsString($row, $content);
        }
    }
}

/**
 * @property int $id
 * @property string $name
 * @property string $name_de
 * @property string $email
 * @property string $password
 * @property bool|null $terms
 * @property int|null $number
 */
class TestActiveRecord extends ActiveRecord implements I18nAttributeInterface
{
    use I18nAttributesTrait;

    #[Override]
    public function init(): void
    {
        $this->i18nAttributes = ['name'];
        parent::init();
    }

    #[Override]
    public function rules(): array
    {
        return $this->getI18nRules([
            [
                ['name'],
                'required',
            ],
            [
                ['name'],
                'string',
                'max' => 255,
            ],
            [
                ['number'],
                'integer',
                'min' => 0,
                'max' => 99,
            ],
            [
                ['email'],
                'email',
            ],
            [
                ['password'],
                SensitiveAttributeValidator::class,
            ],
            [
                ['terms'],
                'boolean',
            ],
        ]);
    }

    #[Override]
    public static function tableName(): string
    {
        return 'fieldset_test';
    }
}
