<?php

declare(strict_types=1);

namespace Hirtz\Skeleton\Helpers;

use Yii;

class CountryList
{
    private static ?array $country = null;

    public static function getNames(): array
    {
        if (null === self::$country) {
            self::$country = [
                'AF' => Yii::t('country', 'AF'),
                'EG' => Yii::t('country', 'EG'),
                'AL' => Yii::t('country', 'AL'),
                'DZ' => Yii::t('country', 'DZ'),
                'AD' => Yii::t('country', 'AD'),
                'AO' => Yii::t('country', 'AO'),
                'AG' => Yii::t('country', 'AG'),
                'GQ' => Yii::t('country', 'GQ'),
                'AR' => Yii::t('country', 'AR'),
                'AM' => Yii::t('country', 'AM'),
                'AZ' => Yii::t('country', 'AZ'),
                'ET' => Yii::t('country', 'ET'),
                'AU' => Yii::t('country', 'AU'),
                'BS' => Yii::t('country', 'BS'),
                'BH' => Yii::t('country', 'BH'),
                'BD' => Yii::t('country', 'BD'),
                'BB' => Yii::t('country', 'BB'),
                'BY' => Yii::t('country', 'BY'),
                'BE' => Yii::t('country', 'BE'),
                'BZ' => Yii::t('country', 'BZ'),
                'BJ' => Yii::t('country', 'BJ'),
                'BT' => Yii::t('country', 'BT'),
                'BO' => Yii::t('country', 'BO'),
                'BA' => Yii::t('country', 'BA'),
                'BW' => Yii::t('country', 'BW'),
                'BR' => Yii::t('country', 'BR'),
                'BN' => Yii::t('country', 'BN'),
                'BG' => Yii::t('country', 'BG'),
                'BF' => Yii::t('country', 'BF'),
                'BI' => Yii::t('country', 'BI'),
                'CL' => Yii::t('country', 'CL'),
                'CN' => Yii::t('country', 'CN'),
                'CR' => Yii::t('country', 'CR'),
                'DK' => Yii::t('country', 'DK'),
                'DE' => Yii::t('country', 'DE'),
                'DM' => Yii::t('country', 'DM'),
                'DO' => Yii::t('country', 'DO'),
                'DJ' => Yii::t('country', 'DJ'),
                'EC' => Yii::t('country', 'EC'),
                'CI' => Yii::t('country', 'CI'),
                'SV' => Yii::t('country', 'SV'),
                'ER' => Yii::t('country', 'ER'),
                'EE' => Yii::t('country', 'EE'),
                'SZ' => Yii::t('country', 'SZ'),
                'FJ' => Yii::t('country', 'FJ'),
                'FI' => Yii::t('country', 'FI'),
                'FR' => Yii::t('country', 'FR'),
                'GA' => Yii::t('country', 'GA'),
                'GM' => Yii::t('country', 'GM'),
                'GE' => Yii::t('country', 'GE'),
                'GH' => Yii::t('country', 'GH'),
                'GD' => Yii::t('country', 'GD'),
                'GR' => Yii::t('country', 'GR'),
                'GT' => Yii::t('country', 'GT'),
                'GN' => Yii::t('country', 'GN'),
                'GW' => Yii::t('country', 'GW'),
                'GY' => Yii::t('country', 'GY'),
                'HT' => Yii::t('country', 'HT'),
                'HN' => Yii::t('country', 'HN'),
                'IN' => Yii::t('country', 'IN'),
                'ID' => Yii::t('country', 'ID'),
                'IQ' => Yii::t('country', 'IQ'),
                'IR' => Yii::t('country', 'IR'),
                'IE' => Yii::t('country', 'IE'),
                'IS' => Yii::t('country', 'IS'),
                'IL' => Yii::t('country', 'IL'),
                'IT' => Yii::t('country', 'IT'),
                'JM' => Yii::t('country', 'JM'),
                'JP' => Yii::t('country', 'JP'),
                'YE' => Yii::t('country', 'YE'),
                'JO' => Yii::t('country', 'JO'),
                'KH' => Yii::t('country', 'KH'),
                'CM' => Yii::t('country', 'CM'),
                'CA' => Yii::t('country', 'CA'),
                'CV' => Yii::t('country', 'CV'),
                'KZ' => Yii::t('country', 'KZ'),
                'QA' => Yii::t('country', 'QA'),
                'KE' => Yii::t('country', 'KE'),
                'KG' => Yii::t('country', 'KG'),
                'KI' => Yii::t('country', 'KI'),
                'CO' => Yii::t('country', 'CO'),
                'KM' => Yii::t('country', 'KM'),
                'CD' => Yii::t('country', 'CD'),
                'CG' => Yii::t('country', 'CG'),
                'KP' => Yii::t('country', 'KP'),
                'KR' => Yii::t('country', 'KR'),
                'HR' => Yii::t('country', 'HR'),
                'CU' => Yii::t('country', 'CU'),
                'KW' => Yii::t('country', 'KW'),
                'LA' => Yii::t('country', 'LA'),
                'LS' => Yii::t('country', 'LS'),
                'LV' => Yii::t('country', 'LV'),
                'LB' => Yii::t('country', 'LB'),
                'LR' => Yii::t('country', 'LR'),
                'LY' => Yii::t('country', 'LY'),
                'LI' => Yii::t('country', 'LI'),
                'LT' => Yii::t('country', 'LT'),
                'LU' => Yii::t('country', 'LU'),
                'MG' => Yii::t('country', 'MG'),
                'MW' => Yii::t('country', 'MW'),
                'MY' => Yii::t('country', 'MY'),
                'MV' => Yii::t('country', 'MV'),
                'ML' => Yii::t('country', 'ML'),
                'MT' => Yii::t('country', 'MT'),
                'MA' => Yii::t('country', 'MA'),
                'MH' => Yii::t('country', 'MH'),
                'MR' => Yii::t('country', 'MR'),
                'MU' => Yii::t('country', 'MU'),
                'MX' => Yii::t('country', 'MX'),
                'FM' => Yii::t('country', 'FM'),
                'MD' => Yii::t('country', 'MD'),
                'MC' => Yii::t('country', 'MC'),
                'MN' => Yii::t('country', 'MN'),
                'ME' => Yii::t('country', 'ME'),
                'MZ' => Yii::t('country', 'MZ'),
                'MM' => Yii::t('country', 'MM'),
                'NA' => Yii::t('country', 'NA'),
                'NR' => Yii::t('country', 'NR'),
                'NP' => Yii::t('country', 'NP'),
                'NZ' => Yii::t('country', 'NZ'),
                'NI' => Yii::t('country', 'NI'),
                'NL' => Yii::t('country', 'NL'),
                'NE' => Yii::t('country', 'NE'),
                'NG' => Yii::t('country', 'NG'),
                'MK' => Yii::t('country', 'MK'),
                'NO' => Yii::t('country', 'NO'),
                'OM' => Yii::t('country', 'OM'),
                'AT' => Yii::t('country', 'AT'),
                'TL' => Yii::t('country', 'TL'),
                'PK' => Yii::t('country', 'PK'),
                'PW' => Yii::t('country', 'PW'),
                'PA' => Yii::t('country', 'PA'),
                'PG' => Yii::t('country', 'PG'),
                'PY' => Yii::t('country', 'PY'),
                'PE' => Yii::t('country', 'PE'),
                'PH' => Yii::t('country', 'PH'),
                'PL' => Yii::t('country', 'PL'),
                'PT' => Yii::t('country', 'PT'),
                'RW' => Yii::t('country', 'RW'),
                'RO' => Yii::t('country', 'RO'),
                'RU' => Yii::t('country', 'RU'),
                'SB' => Yii::t('country', 'SB'),
                'ZM' => Yii::t('country', 'ZM'),
                'WS' => Yii::t('country', 'WS'),
                'SM' => Yii::t('country', 'SM'),
                'ST' => Yii::t('country', 'ST'),
                'SA' => Yii::t('country', 'SA'),
                'SE' => Yii::t('country', 'SE'),
                'CH' => Yii::t('country', 'CH'),
                'SN' => Yii::t('country', 'SN'),
                'RS' => Yii::t('country', 'RS'),
                'SC' => Yii::t('country', 'SC'),
                'SL' => Yii::t('country', 'SL'),
                'ZW' => Yii::t('country', 'ZW'),
                'SG' => Yii::t('country', 'SG'),
                'SK' => Yii::t('country', 'SK'),
                'SI' => Yii::t('country', 'SI'),
                'SO' => Yii::t('country', 'SO'),
                'ES' => Yii::t('country', 'ES'),
                'LK' => Yii::t('country', 'LK'),
                'KN' => Yii::t('country', 'KN'),
                'LC' => Yii::t('country', 'LC'),
                'VC' => Yii::t('country', 'VC'),
                'ZA' => Yii::t('country', 'ZA'),
                'SD' => Yii::t('country', 'SD'),
                'SS' => Yii::t('country', 'SS'),
                'SR' => Yii::t('country', 'SR'),
                'SY' => Yii::t('country', 'SY'),
                'TJ' => Yii::t('country', 'TJ'),
                'TZ' => Yii::t('country', 'TZ'),
                'TH' => Yii::t('country', 'TH'),
                'TG' => Yii::t('country', 'TG'),
                'TO' => Yii::t('country', 'TO'),
                'TT' => Yii::t('country', 'TT'),
                'TD' => Yii::t('country', 'TD'),
                'CZ' => Yii::t('country', 'CZ'),
                'TN' => Yii::t('country', 'TN'),
                'TR' => Yii::t('country', 'TR'),
                'TM' => Yii::t('country', 'TM'),
                'TV' => Yii::t('country', 'TV'),
                'UG' => Yii::t('country', 'UG'),
                'UA' => Yii::t('country', 'UA'),
                'HU' => Yii::t('country', 'HU'),
                'UY' => Yii::t('country', 'UY'),
                'UZ' => Yii::t('country', 'UZ'),
                'VU' => Yii::t('country', 'VU'),
                'VE' => Yii::t('country', 'VE'),
                'AE' => Yii::t('country', 'AE'),
                'US' => Yii::t('country', 'US'),
                'GB' => Yii::t('country', 'GB'),
                'VN' => Yii::t('country', 'VN'),
                'CF' => Yii::t('country', 'CF'),
                'CY' => Yii::t('country', 'CY'),
            ];

            asort(self::$country);
        }

        return self::$country;
    }

    public static function getName(string $code): ?string
    {
        $names = self::getNames();
        return $names[$code] ?? null;
    }
}
