<?php

declare(strict_types=1);

namespace Hirtz\Skeleton\Tests\Widgets\Forms;

use Hirtz\Skeleton\Html\Div;
use Hirtz\Skeleton\Test\TestCase;
use Hirtz\Skeleton\Validators\DynamicRangeValidator;
use Hirtz\Skeleton\Widgets\Forms\ActiveForm;
use Hirtz\Skeleton\Widgets\Forms\Fieldset;
use Override;
use yii\base\InvalidConfigException;
use yii\base\Model;

class ActiveFormTest extends TestCase
{
    public function testAttributeWithAutogeneratedFields(): void
    {
        $form = ActiveForm::make()
            ->model(new TestModel());

        $label = '<div class="form-label"><label class="label" for="testmodel-number">Number</label>';
        $number = '<div class="form-content"><input type="number" id="testmodel-number" class="input" name="TestModel[number]" max="100"></div>';
        $text = '<div class="form-content"><input type="text" id="testmodel-text" class="input" name="TestModel[text]" maxlength="50" minlength="50"></div>';
        $select = '<select id="testmodel-value" class="input" name="TestModel[value]"><option value="value1">Value 1</option><option value="value2">Value 2</option><option value="value3">Value 3</option></select>';

        $content = $form->render();

        self::assertStringContainsString($label, $content);
        self::assertStringContainsString($number, $content);
        self::assertStringContainsString($text, $content);
        self::assertStringContainsString($select, $content);
    }

    public function testAttributeWithMultipleFieldsets(): void
    {
        $form = ActiveForm::make()
            ->model(new TestModel())
            ->rows([
                [
                    Div::make()->content('Block 1'),
                    'number',
                ],
                [
                    Div::make()->content('Block 2'),
                    'text',
                ],
                [
                    'invalid',
                ],
            ]);

        $content = $form->render();

        self::assertStringContainsString('Block 1', $content);
        self::assertStringContainsString('<div class="form-label"><label class="label" for="testmodel-number">Number</label>', $content);
        self::assertStringContainsString('Block 2', $content);
        self::assertStringContainsString('<div class="form-label"><label class="label" for="testmodel-text">Text</label>', $content);
        self::assertStringNotContainsString('invalid', $content);
    }

    /**
     * A fieldset caches its render, so each pass builds its own rather than reordering the same two.
     */
    public function testEveryFieldsetIsBoundToTheForm(): void
    {
        $properties = ['number', 'text'];

        foreach ([$properties, array_reverse($properties)] as $order) {
            $content = ActiveForm::make()
                ->model(new TestModel())
                ->rows(array_map(
                    static fn (string $property): Fieldset => Fieldset::make()->rows([$property]),
                    $order,
                ))
                ->render();

            self::assertStringContainsString('name="TestModel[number]"', $content);
            self::assertStringContainsString('name="TestModel[text]"', $content);
            self::assertSame(2, substr_count($content, '<fieldset'));
        }
    }

    public function testRowsAreNormalizedToFieldsets(): void
    {
        $form = ActiveForm::make()
            ->model(new TestModel())
            ->rows(['number', 'text']);

        $form->rows(function (array $rows): array {
            self::assertCount(1, $rows);
            self::assertSame(['number', 'text'], $rows[0]->getRows());

            return $rows;
        });

        $form->render();
    }

    /**
     * The shape used to be sniffed off the first row and the answer applied to the rest, so a bare field behind a
     * group was handed to a fieldset that never got its model — a fatal, one row order away (#120).
     */
    public function testMixingGroupsAndBareFieldsIsRefused(): void
    {
        $this->expectException(InvalidConfigException::class);

        ActiveForm::make()
            ->model(new TestModel())
            ->rows([
                ['number'],
                'text',
            ]);
    }
}

class TestModel extends Model
{
    public ?string $number = null;
    public ?string $text = null;
    public ?string $invalid = null;
    public ?string $value = null;

    #[Override]
    public function rules(): array
    {
        return [
            [
                ['number'],
                'integer',
                'max' => 100,
            ],
            [
                ['text'],
                'string',
                'length' => 50,
            ],
            [
                ['value'],
                DynamicRangeValidator::class,
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public static function getValues(): array
    {
        return [
            'value1' => 'Value 1',
            'value2' => 'Value 2',
            'value3' => 'Value 3',
        ];
    }
}
