<?php

declare(strict_types=1);

namespace Hirtz\Skeleton\Tests\Widgets\Forms;

use Hirtz\Skeleton\Db\ActiveRecord;
use Hirtz\Skeleton\Db\I18nActiveQuery;
use Hirtz\Skeleton\Models\Interfaces\I18nAttributeInterface;
use Hirtz\Skeleton\Models\Interfaces\TranslationInterface;
use Hirtz\Skeleton\Models\Traits\I18nAttributesTrait;
use Hirtz\Skeleton\Models\Traits\TranslationTrait;
use Hirtz\Skeleton\Models\Translation;
use Hirtz\Skeleton\Test\TestCase;
use Hirtz\Skeleton\Validators\SensitiveAttributeValidator;
use Hirtz\Skeleton\Widgets\Forms\Fields\InputField;
use Hirtz\Skeleton\Widgets\Forms\Fieldset;
use Override;
use Yii;

class FieldsetTest extends TestCase
{
    #[Override]
    protected function setUp(): void
    {
        parent::setUp();

        Yii::$app->getI18n()->setLanguages(['en-US', 'de']);

        $columns = [
            'id' => 'pk',
            'name' => 'string not null',
            'email' => 'string null',
            'password' => 'string null',
            'terms' => 'boolean null',
            'number' => 'integer(2) unsigned not null',
        ];

        Yii::$app->getDb()->createCommand()
            ->createTable(TestActiveRecord::tableName(), $columns)
            ->execute();

        Yii::$app->getDb()->createCommand()
            ->insert(TestActiveRecord::tableName(), [
                'name' => 'Test Name',
                'number' => 42,
            ])->execute();

        Yii::$app->getDb()->createCommand()
            ->insert(Translation::tableName(), [
                'model' => TestActiveRecord::class,
                'model_id' => 1,
                'language' => 'de',
                'attribute' => 'name',
                'value' => 'Test Name DE',
            ])->execute();
    }

    /**
     * `CREATE TABLE` commits the test transaction, so the translation is removed by hand.
     */
    #[Override]
    protected function tearDown(): void
    {
        Translation::deleteAll(['model' => TestActiveRecord::class]);

        Yii::$app->getDb()->createCommand()
            ->dropTable(TestActiveRecord::tableName())
            ->execute();

        parent::tearDown();
    }

    public function testAutogeneratedFields(): void
    {
        $model = TestActiveRecord::findOne(1);

        $content = Fieldset::make()
            ->model($model)
            ->rows([
                'name',
                'number',
                'email',
                'password',
                'terms',
            ])
            ->render();

        $expected = '<div class="form-group form-row" data-id="testactiverecord-name"><div class="form-label"><label class="label" for="testactiverecord-name">Name</label></div><div class="form-content"><input type="text" id="testactiverecord-name" class="input" name="TestActiveRecord[name]" value="Test Name" maxlength="255" required></div></div>';
        self::assertStringContainsString($expected, $content);

        $expected = '<div class="form-group form-row" data-id="testactiverecord-name-de"><div class="form-label"><label class="label" for="testactiverecord-name-de">Name (DE)</label></div><div class="form-content"><input type="text" id="testactiverecord-name-de" class="input" name="TestActiveRecord[name_de]" value="Test Name DE" maxlength="255" required></div></div>';
        self::assertStringContainsString($expected, $content);

        $expected = '<div class="form-group form-row" data-id="testactiverecord-email"><div class="form-label"><label class="label" for="testactiverecord-email">Email</label></div><div class="form-content"><input type="email" id="testactiverecord-email" class="input" name="TestActiveRecord[email]"></div></div>';
        self::assertStringContainsString($expected, $content);

        $expected = '<div class="form-group form-row" data-id="testactiverecord-password"><div class="form-label"><label class="label" for="testactiverecord-password">Password</label></div><div class="form-content"><input type="password" id="testactiverecord-password" class="input" name="TestActiveRecord[password]"></div></div>';
        self::assertStringContainsString($expected, $content);

        $expected = '<div class="form-checkbox-row form-group form-row" data-id="testactiverecord-terms"><div class="form-content"><div class="checkbox"><input type="checkbox" id="testactiverecord-terms" class="input" name="TestActiveRecord[terms]" value="1"></div><div><label class="label" for="testactiverecord-terms">Terms</label></div></div></div>';
        self::assertStringContainsString($expected, $content);
    }

    public function testI18nFields(): void
    {
        $model = TestActiveRecord::findOne(1);

        $fieldset = Fieldset::make()
            ->model($model)
            ->rows([
                InputField::make()
                    ->property('name')
                    ->model($model)
                    ->prepare(fn (InputField $field) => $field->value($field->language)),
            ]);

        $expected = '<div class="form-group form-row" data-id="testactiverecord-name"><div class="form-label"><label class="label" for="testactiverecord-name">Name</label></div><div class="form-content"><input type="text" id="testactiverecord-name" class="input" name="TestActiveRecord[name]" value="en-US" maxlength="255" required></div></div>';
        self::assertStringContainsString($expected, $fieldset->render());

        $expected = '<div class="form-group form-row" data-id="testactiverecord-name-de"><div class="form-label"><label class="label" for="testactiverecord-name-de">Name (DE)</label></div><div class="form-content"><input type="text" id="testactiverecord-name-de" class="input" name="TestActiveRecord[name_de]" value="de" maxlength="255" required></div></div>';
        self::assertStringContainsString($expected, $fieldset->render());
    }
}

/**
 * @property int $id
 * @property string $name
 * @property string|null $name_de
 * @property string $email
 * @property string $password
 * @property bool|null $terms
 * @property int|null $number
 */
class TestActiveRecord extends ActiveRecord implements I18nAttributeInterface, TranslationInterface
{
    use I18nAttributesTrait;
    use TranslationTrait;

    #[Override]
    public function init(): void
    {
        $this->i18nAttributes = ['name'];
        parent::init();
    }

    public function getTranslationModelClass(): string
    {
        return self::class;
    }

    /**
     * @return I18nActiveQuery<static>
     */
    #[Override]
    public static function find(): I18nActiveQuery
    {
        return Yii::createObject(I18nActiveQuery::class, [static::class]);
    }

    #[Override]
    public function rules(): array
    {
        return $this->getI18nRules([
            [
                ['name'],
                'required',
            ],
            [
                ['name'],
                'string',
                'max' => 255,
            ],
            [
                ['number'],
                'integer',
                'min' => 0,
                'max' => 99,
            ],
            [
                ['email'],
                'email',
            ],
            [
                ['password'],
                SensitiveAttributeValidator::class,
            ],
            [
                ['terms'],
                'boolean',
            ],
        ]);
    }

    #[Override]
    public static function tableName(): string
    {
        return 'fieldset_test';
    }
}
