<?php

declare(strict_types=1);

namespace Hirtz\Skeleton\Migrations;

use yii\db\Migration;

/**
 * The squashed schema of this bundle, generated by `bin/baseline` from a fully migrated database.
 *
 * A fresh install runs this and nothing before it. An upgraded project never runs it: the collapse
 * writes this class into `migration` instead, having deleted the v2 rows it replaces.
 *
 * Raw SQL rather than the schema builder, and deliberately: the point of generating from a grown
 * database is that the fresh schema is what an upgraded one has, and a rewrite through the builder is
 * a chance for the two to differ. Regenerate rather than edit.
 *
 * The foreign keys come after every table, because `product` and `product_variant` reference each
 * other and no single `CREATE TABLE` can say that.
 *
 * @noinspection PhpUnused
 */
class M260101000000SkeletonBaseline extends Migration
{
    public function safeUp(): void
    {
        $this->execute(<<<'SQL'
            CREATE TABLE `auth_rule` (
              `name` varchar(64) NOT NULL,
              `data` blob DEFAULT NULL,
              `created_at` int(11) DEFAULT NULL,
              `updated_at` int(11) DEFAULT NULL,
              PRIMARY KEY (`name`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `auth_item` (
              `name` varchar(64) NOT NULL,
              `type` smallint(6) NOT NULL,
              `description` text DEFAULT NULL,
              `rule_name` varchar(64) DEFAULT NULL,
              `data` blob DEFAULT NULL,
              `updated_at` int(11) DEFAULT NULL,
              `created_at` int(11) NOT NULL,
              PRIMARY KEY (`name`),
              KEY `auth_item_rule_name_ibfk` (`rule_name`),
              KEY `type` (`type`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `auth_item_child` (
              `parent` varchar(64) NOT NULL,
              `child` varchar(64) NOT NULL,
              PRIMARY KEY (`parent`,`child`),
              KEY `auth_item_child_child_ibfk` (`child`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `auth_assignment` (
              `item_name` varchar(64) NOT NULL,
              `user_id` int(11) unsigned NOT NULL,
              `created_at` int(11) DEFAULT NULL,
              PRIMARY KEY (`item_name`,`user_id`),
              KEY `auth_assignment_user_id_ibfk` (`user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `user` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` tinyint(1) NOT NULL DEFAULT 1,
              `name` varchar(32) NOT NULL,
              `email` varchar(100) NOT NULL,
              `email_confirmed_at` datetime DEFAULT NULL,
              `password_hash` varchar(100) DEFAULT NULL,
              `password_scheme` varchar(10) DEFAULT NULL,
              `language` varchar(5) NOT NULL DEFAULT 'en-US',
              `timezone` varchar(100) DEFAULT NULL,
              `show_hints` tinyint(1) unsigned NOT NULL DEFAULT 1,
              `color_scheme` varchar(5) DEFAULT NULL,
              `auth_key` varchar(32) NOT NULL,
              `two_factor_secret` varchar(255) DEFAULT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              `is_owner` tinyint(1) unsigned DEFAULT 0,
              `created_by_user_id` int(11) unsigned DEFAULT NULL,
              `login_count` int(11) unsigned NOT NULL DEFAULT 0,
              `last_login` datetime DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `email` (`email`),
              UNIQUE KEY `name` (`name`),
              KEY `status` (`status`),
              KEY `user_created_by_user_id_ibfk` (`created_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `user_login` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `user_id` int(11) unsigned NOT NULL,
              `browser` varchar(255) DEFAULT NULL,
              `ip_address` varbinary(16) DEFAULT NULL,
              `created_at` datetime NOT NULL,
              `type` tinyint(3) unsigned NOT NULL DEFAULT 1,
              PRIMARY KEY (`id`),
              KEY `user_id` (`user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `user_token` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `user_id` int(11) unsigned NOT NULL,
              `type` varchar(16) NOT NULL,
              `token` varchar(64) NOT NULL,
              `expires_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `token` (`token`),
              KEY `user_id` (`user_id`,`type`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `session` (
              `id` char(64) NOT NULL,
              `user_id` int(11) unsigned DEFAULT NULL,
              `ip_address` varbinary(16) DEFAULT NULL,
              `expire` int(11) unsigned DEFAULT NULL,
              `data` longblob DEFAULT NULL,
              PRIMARY KEY (`id`),
              KEY `user_id` (`user_id`),
              KEY `expire` (`expire`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `redirect` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `type` smallint(6) NOT NULL DEFAULT 301,
              `request_uri` varchar(250) NOT NULL,
              `url` varchar(250) NOT NULL,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `request_uri` (`request_uri`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `trail` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `type` smallint(6) unsigned NOT NULL DEFAULT 13,
              `model_class` varchar(255) DEFAULT NULL,
              `model_id` varchar(64) DEFAULT NULL,
              `user_id` int(11) unsigned DEFAULT NULL,
              `message` varchar(255) DEFAULT NULL,
              `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`data`)),
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              KEY `user_id` (`user_id`),
              KEY `model_class` (`model_class`,`model_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `translation` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `model_class` varchar(255) NOT NULL,
              `model_id` bigint(20) unsigned NOT NULL,
              `language` varchar(16) NOT NULL,
              `attribute` varchar(64) NOT NULL,
              `value` text DEFAULT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `model_class` (`model_class`,`model_id`,`language`,`attribute`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `search` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `model_class` varchar(255) NOT NULL,
              `model_id` bigint(20) unsigned NOT NULL,
              `language` varchar(16) NOT NULL,
              `tenant_id` int(11) unsigned DEFAULT NULL,
              `status` tinyint(3) NOT NULL DEFAULT 1,
              `weight` decimal(4,2) NOT NULL DEFAULT 1.00,
              `title` varchar(255) NOT NULL,
              `content` mediumtext DEFAULT NULL,
              `updated_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `model` (`model_class`,`model_id`,`language`),
              KEY `tenant` (`tenant_id`,`status`,`language`),
              FULLTEXT KEY `title` (`title`),
              FULLTEXT KEY `content` (`title`,`content`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `auth_item` ADD CONSTRAINT `auth_item_rule_name_ibfk` FOREIGN KEY (`rule_name`) REFERENCES `auth_rule` (`name`) ON DELETE SET NULL ON UPDATE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `auth_item_child` ADD CONSTRAINT `auth_item_child_child_ibfk` FOREIGN KEY (`child`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `auth_item_child` ADD CONSTRAINT `auth_item_child_parent_ibfk` FOREIGN KEY (`parent`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `auth_assignment` ADD CONSTRAINT `auth_assignment_item_name_ibfk` FOREIGN KEY (`item_name`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `auth_assignment` ADD CONSTRAINT `auth_assignment_user_id_ibfk` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `user` ADD CONSTRAINT `user_created_by_user_id_ibfk` FOREIGN KEY (`created_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `user_login` ADD CONSTRAINT `login_user_id_ibfk` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `user_token` ADD CONSTRAINT `user_token_user_id_ibfk` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `session` ADD CONSTRAINT `session_user_id_ibfk` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            INSERT INTO `auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `updated_at`, `created_at`) VALUES
              ('admin', '1', NULL, NULL, NULL, '1789985566', '1789985566'),
              ('authUpdate', '2', '{\"category\":\"skeleton\",\"key\":\"AUTH_AUTH_UPDATE_DESCRIPTION\"}', NULL, NULL, '1789985566', '1789985566'),
              ('manager', '1', NULL, NULL, NULL, '1789985582', '1789985582'),
              ('redirect', '2', '{\"category\":\"skeleton\",\"key\":\"AUTH_REDIRECT_DESCRIPTION\"}', NULL, NULL, '1789985581', '1789985581'),
              ('system', '2', '{\"category\":\"skeleton\",\"key\":\"AUTH_SYSTEM_DESCRIPTION\"}', NULL, NULL, '1789985582', '1789985582'),
              ('trailIndex', '2', '{\"category\":\"skeleton\",\"key\":\"AUTH_TRAIL_INDEX_DESCRIPTION\"}', NULL, NULL, '1789985570', '1789985570'),
              ('user', '2', '{\"category\":\"skeleton\",\"key\":\"AUTH_USER_DESCRIPTION\"}', NULL, NULL, '1789985581', '1789985581')
            SQL);

        $this->execute(<<<'SQL'
            INSERT INTO `auth_item_child` (`parent`, `child`) VALUES
              ('admin', 'authUpdate'),
              ('manager', 'authUpdate'),
              ('admin', 'redirect'),
              ('manager', 'redirect'),
              ('admin', 'system'),
              ('admin', 'trailIndex'),
              ('manager', 'trailIndex'),
              ('admin', 'user'),
              ('manager', 'user')
            SQL);
    }

    public function safeDown(): bool
    {
        echo "    > a baseline cannot be reverted, restore a dump instead\n";

        return false;
    }
}
